name: Push Folder

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push changed file
      uses: adu013/copy_file_to_another_repo_action@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'test_files'
        destination_repo: '<username>/<repo_name>'
        user_email: '<user_email>'
        user_name: '<username>'
        commit_msg: '[GHA] Update the test files.'
